export * from "./tags.ts";
export * from "./recourses.ts";
export * from "./difficulty.ts";
export * from "./manaPoints.ts";
export * from "./healthPoints.ts";
export * from "./armor.ts";
export * from "./attackSpeed.ts";
export * from "./moveSpeed.ts";
export * from "./range.ts";
